/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWfhRouteImport } from './routes/app.wfh'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppLeaveRouteImport } from './routes/app.leave'
import { Route as AppHolidaysRouteImport } from './routes/app.holidays'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAdminTaskManagementRouteImport } from './routes/app.admin.task-management'
import { Route as AppAdminSettingsRouteImport } from './routes/app.admin.settings'
import { Route as AppAdminHolidaysRouteImport } from './routes/app.admin.holidays'
import { Route as AppAdminEmployeesRouteImport } from './routes/app.admin.employees'
import { Route as AppAdminAttendanceRouteImport } from './routes/app.admin.attendance'
import { Route as AppAdminApprovalsRouteImport } from './routes/app.admin.approvals'
import { Route as AppAdminEmployeesIdRouteImport } from './routes/app.admin.employees.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWfhRoute = AppWfhRouteImport.update({
  id: '/wfh',
  path: '/wfh',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRoute = AppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppHolidaysRoute = AppHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTaskManagementRoute = AppAdminTaskManagementRouteImport.update({
  id: '/task-management',
  path: '/task-management',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminHolidaysRoute = AppAdminHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEmployeesRoute = AppAdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAttendanceRoute = AppAdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminApprovalsRoute = AppAdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEmployeesIdRoute = AppAdminEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminEmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/attendance': typeof AppAttendanceRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/holidays': typeof AppHolidaysRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/wfh': typeof AppWfhRoute
  '/app/admin/approvals': typeof AppAdminApprovalsRoute
  '/app/admin/attendance': typeof AppAdminAttendanceRoute
  '/app/admin/employees': typeof AppAdminEmployeesRouteWithChildren
  '/app/admin/holidays': typeof AppAdminHolidaysRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/task-management': typeof AppAdminTaskManagementRoute
  '/app/admin/employees/$id': typeof AppAdminEmployeesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/attendance': typeof AppAttendanceRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/holidays': typeof AppHolidaysRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/wfh': typeof AppWfhRoute
  '/app/admin/approvals': typeof AppAdminApprovalsRoute
  '/app/admin/attendance': typeof AppAdminAttendanceRoute
  '/app/admin/employees': typeof AppAdminEmployeesRouteWithChildren
  '/app/admin/holidays': typeof AppAdminHolidaysRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/task-management': typeof AppAdminTaskManagementRoute
  '/app/admin/employees/$id': typeof AppAdminEmployeesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/attendance': typeof AppAttendanceRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/holidays': typeof AppHolidaysRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/wfh': typeof AppWfhRoute
  '/app/admin/approvals': typeof AppAdminApprovalsRoute
  '/app/admin/attendance': typeof AppAdminAttendanceRoute
  '/app/admin/employees': typeof AppAdminEmployeesRouteWithChildren
  '/app/admin/holidays': typeof AppAdminHolidaysRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/task-management': typeof AppAdminTaskManagementRoute
  '/app/admin/employees/$id': typeof AppAdminEmployeesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/attendance'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/holidays'
    | '/app/leave'
    | '/app/profile'
    | '/app/tasks'
    | '/app/wfh'
    | '/app/admin/approvals'
    | '/app/admin/attendance'
    | '/app/admin/employees'
    | '/app/admin/holidays'
    | '/app/admin/settings'
    | '/app/admin/task-management'
    | '/app/admin/employees/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/attendance'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/holidays'
    | '/app/leave'
    | '/app/profile'
    | '/app/tasks'
    | '/app/wfh'
    | '/app/admin/approvals'
    | '/app/admin/attendance'
    | '/app/admin/employees'
    | '/app/admin/holidays'
    | '/app/admin/settings'
    | '/app/admin/task-management'
    | '/app/admin/employees/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/attendance'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/holidays'
    | '/app/leave'
    | '/app/profile'
    | '/app/tasks'
    | '/app/wfh'
    | '/app/admin/approvals'
    | '/app/admin/attendance'
    | '/app/admin/employees'
    | '/app/admin/holidays'
    | '/app/admin/settings'
    | '/app/admin/task-management'
    | '/app/admin/employees/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wfh': {
      id: '/app/wfh'
      path: '/wfh'
      fullPath: '/app/wfh'
      preLoaderRoute: typeof AppWfhRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leave': {
      id: '/app/leave'
      path: '/leave'
      fullPath: '/app/leave'
      preLoaderRoute: typeof AppLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/holidays': {
      id: '/app/holidays'
      path: '/holidays'
      fullPath: '/app/holidays'
      preLoaderRoute: typeof AppHolidaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/task-management': {
      id: '/app/admin/task-management'
      path: '/task-management'
      fullPath: '/app/admin/task-management'
      preLoaderRoute: typeof AppAdminTaskManagementRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/holidays': {
      id: '/app/admin/holidays'
      path: '/holidays'
      fullPath: '/app/admin/holidays'
      preLoaderRoute: typeof AppAdminHolidaysRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/employees': {
      id: '/app/admin/employees'
      path: '/employees'
      fullPath: '/app/admin/employees'
      preLoaderRoute: typeof AppAdminEmployeesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/attendance': {
      id: '/app/admin/attendance'
      path: '/attendance'
      fullPath: '/app/admin/attendance'
      preLoaderRoute: typeof AppAdminAttendanceRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/approvals': {
      id: '/app/admin/approvals'
      path: '/approvals'
      fullPath: '/app/admin/approvals'
      preLoaderRoute: typeof AppAdminApprovalsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/employees/$id': {
      id: '/app/admin/employees/$id'
      path: '/$id'
      fullPath: '/app/admin/employees/$id'
      preLoaderRoute: typeof AppAdminEmployeesIdRouteImport
      parentRoute: typeof AppAdminEmployeesRoute
    }
  }
}

interface AppAdminEmployeesRouteChildren {
  AppAdminEmployeesIdRoute: typeof AppAdminEmployeesIdRoute
}

const AppAdminEmployeesRouteChildren: AppAdminEmployeesRouteChildren = {
  AppAdminEmployeesIdRoute: AppAdminEmployeesIdRoute,
}

const AppAdminEmployeesRouteWithChildren =
  AppAdminEmployeesRoute._addFileChildren(AppAdminEmployeesRouteChildren)

interface AppAdminRouteChildren {
  AppAdminApprovalsRoute: typeof AppAdminApprovalsRoute
  AppAdminAttendanceRoute: typeof AppAdminAttendanceRoute
  AppAdminEmployeesRoute: typeof AppAdminEmployeesRouteWithChildren
  AppAdminHolidaysRoute: typeof AppAdminHolidaysRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminTaskManagementRoute: typeof AppAdminTaskManagementRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminApprovalsRoute: AppAdminApprovalsRoute,
  AppAdminAttendanceRoute: AppAdminAttendanceRoute,
  AppAdminEmployeesRoute: AppAdminEmployeesRouteWithChildren,
  AppAdminHolidaysRoute: AppAdminHolidaysRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminTaskManagementRoute: AppAdminTaskManagementRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHolidaysRoute: typeof AppHolidaysRoute
  AppLeaveRoute: typeof AppLeaveRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWfhRoute: typeof AppWfhRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAttendanceRoute: AppAttendanceRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHolidaysRoute: AppHolidaysRoute,
  AppLeaveRoute: AppLeaveRoute,
  AppProfileRoute: AppProfileRoute,
  AppTasksRoute: AppTasksRoute,
  AppWfhRoute: AppWfhRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
